KingsburyLab/pyEQL

CHANGELOG.md, docs/tutorial.md, setup.cfg, src/pyEQL/__init__.py, src/pyEQL/activity_correction.py, src/pyEQL/engines.py, src/pyEQL/equilibrium.py, src/pyEQL/functions.py, src/pyEQL/solution.py, tests/test_effective_pitzer.py, tests/test_solute_properties.py, tests/test_solution.py
rename pyEQL's internal registry from `unit` to `ureg`. This accomplishes two things:
1. Reduce the likelihood of name collisions when `unit` or `units` is used as a kwarg in a function call
2. Make use of `Quantity` within pyEQL entirely consistent with the `pint` documentation, which almost always assigns the unit registry to the variable `ureg`.
=> rename UnitRegistry from unit -> ureg

src/pyEQL/__init__.py
Add a deprecation warning to `from pyEQL import unit`
=> UnitRegistry: add deprecation warning for ureg

src/pyEQL/engines.py, src/pyEQL/solution.py, tests/test_solution.py
This PR adds the ability to pass an `EOS` instance as an `engine` kwarg to `Solution`, rather than just strings. This opens the possibility to pass customized `EOS` classes that have not been hard-coded into `Solution.__init__`.
It also fixes a small bug in which the `NativeEOS` was not properly ignoring `HOH` as the salt in very dilute solutions.
=> Solution: enable passing EOS instance as engine

.github/release.yml, .github/workflows/post-process.yml, README.md
- Prevent duplicate GitHub release being created
- add Zenodo badge to README
=> CI enhancements and Zenodo badge

CHANGELOG.md, src/pyEQL/engines.py, src/pyEQL/equilibrium.py, src/pyEQL/solution.py, tests/test_phreeqc.py, tests/test_volume_concentration.py
Adds an `engine` class that directly uses `phreeqpython` to compute activity coefficients in addition to speciation (which is used in the `NativeEOS` as well).
This engine currently returns a unit osmotic coefficient and 0 partial molar volume for all solutes, which _appears_ to be consistent with the way `phreeqpython` behaves (at least using the non-pitzer databases), but more work may be required on this in the future.
**Subtle but important change** - the `pH` attribute of `Solution` is now calculated based only on the H+ concentration, not its activity.
=> add PhreeqcEOS electrolyte modeling engine

CHANGELOG.md, setup.cfg, src/pyEQL/solution.py, src/pyEQL/utils.py, tests/test_solution.py
Although `as_dict` / `from_dict` work properly, serialization to `json` does not, because `Quantity` objects do not serialize automatically. This PR fixes that by converting them to str in `as_dict`. Also bumps python version.
=> Fix Solution serialization

.github/workflows/post-process.yml, .github/workflows/testing.yaml, .github/workflows/upgrade_dependencies.yml, CHANGELOG.md, README.md, docs/conf.py, setup.cfg, src/pyEQL/utils.py
following `numpy` and `pymatgen`
=> Drop python 3.8 support

CHANGELOG.md, src/pyEQL/__init__.py
Removes the machinery to automatically redirect `pyEQL.unit` to `pyEQL.ureg`. This caused a noisy warning anytime pyEQL was imported. The rename happened in v0.6.1.
=> remove pyEQL.unit deprecation warning

CHANGELOG.md, src/pyEQL/utils.py, tests/test_utils.py
Major changes:
- Add in the utility method `format_solute` to format a solute dictionary with the provided unit. (Closes #53)
If this is work in progress, what else needs to be done?
- Need help with the documentation
```sh
```
=> Add utility method to format dictionary

AUTHORS.md, CHANGELOG.md, setup.cfg, src/pyEQL/__init__.py, src/pyEQL/engines.py, src/pyEQL/equilibrium.py, src/pyEQL/solution.py, src/pyEQL/utils.py, tests/test_phreeqc.py
Miscellaneous changes to improve pyEQL's speed. Reduces the time required for many common operations by 3x - 10x.
Major changes:
- reduce calls to `ureg.Quantity` by using magnitudes where feasible
- use `Quantity(float, 'unit') instead of `Quantity('float unit') which is substantially faster
- Instantiate and connect to the native database in `pyEQL.__init__` to speed up subsequent access by `Solution` objects
- expand use of `lru_cache` for solution properties
- various minor optimizations
Results (results of `%%timeit` (ms), before / after)
1. Instantiate a 2 mol/L NaCl `Solution`: 301 / 84
2. `s.get_activity_coefficient('Na+')`: 27 / 14
3. `s.conductivity`: 143 / 44
4. `s.ionic_strength`: 5 / 0.5
5. `s.get_transport_number('Na+'): 2.4 / 0.5
=> Performance Improvements

README.md, docs/database.md
This is the world's tiniest PR to fix an incorrectly formatted markdown link in the README :)
Old way: [](https://pyscaffold.org/).
New way: [https://pyscaffold.org/]()
Plus a small grammar fix.
=> Fix link in README to pyscaffold

CHANGELOG.md, examples/pyeql_demo.ipynb, src/pyEQL/logging_system.py
`pyEQL` used to have a filter to suppress duplicate log messages (i.e., to ensure each log message was unique). This was inadvertently deactivated during the package overhaul before 0.6.0, leading to a distracting amount of log messages (see #52 and #64 )
=> Restore duplicate log filtering

CHANGELOG.md, presets/Ringers lactate.yaml, presets/normal saline.yaml, presets/rainwater.yaml, presets/seawater.yaml, presets/urine.yaml, presets/wastewater.yaml, src/pyEQL/functions.py, src/pyEQL/solution.py, tests/test_solution.py
Issue #63
Major changes: 
- Added `from_preset` Class Method to Solution - this new method allows for the instantiation of a `Solution` object directly from predefined presets stored in yaml or json files.
- Added methods `from_file` and `to_file` for more convenient save and load Solution object to or from json or yaml files.
If this is work in progress, what else needs to be done?
```sh
```
=>  Replace autogenerate() with a Solution class method

CHANGELOG.md, src/pyEQL/activity_correction.py, src/pyEQL/solution.py, src/pyEQL/utils.py, tests/test_utils.py
Use `IAPWS97` water model instead of `IAPWS95` when possible, because the former instantiates much more quickly. Also create a utility function `create_water_substance` with caching to speed up access to these instances.
=> Use IAPWS97 for speed; cache instance via utility function

CHANGELOG.md, src/pyEQL/engines.py, src/pyEQL/solution.py, tests/test_phreeqc.py
Sometimes, `equilibrate` would mess up the charge balance even when a solution was initially electroneutral. This was especially true when `balance_charge` was equal to something other than `pH`
=> equilibrate(): fix charge balancing bugs in Native and PhreeqC engines

src/pyEQL/solution.py
Reverts change to `Solution.__add__` in #92 . Any class that inherits from `Solution` is not guaranteed to have the same call signature in `__init__`, so such classes will probably need to re-implement `__add__` anyway. Explicitly invoking the classname `Solution` rather than impliciltly (`self.__class__`) seems to be more consistent with how magic methods are usually implemented.
=> Revert change to __add__

CHANGELOG.md, src/pyEQL/solution.py, tests/test_solution.py
Fixes a bug in which, due to a stray set of quotation marks, `get_total_amount` would fail with mass-based units:
```
1200             TOT += amt * ion.get_el_amt_dict()[el]  # returns {el: mol per formula unit}
1202         elif ureg.Quantity(units).dimensionality in (
1203             "[mass]",
1204             "[mass]/[length]**3",
1205             "[mass]/[mass]",
1206         ):
-> 1207             TOT += amt * ion.to_weight_dict["el"]  # returns {el: wt fraction}
1209 return TOT
KeyError: 'el'
```
=> Solution.get_total_amount: bufix for mass based units

CHANGELOG.md, src/pyEQL/equilibrium.py, tests/test_equilibrium.py
Fixes incorrect calculation results from `equilibrium.alpha`. Note that this utility function is currently provided only as a convenience; it is not utilized anywhere within `pyEQL` at present.
=> alpha: fix incorrect calculation

.github/workflows/post-process.yml, .github/workflows/testing.yaml, CHANGELOG.md, docs/engines.md, docs/installation.md, src/pyEQL/engines.py, src/pyEQL/solution.py, src/pyEQL/utils.py, tests/test_activity.py, tests/test_functions.py, tests/test_phreeqc.py, tests/test_salt_matching.py, tests/test_solution.py
Partially addresses #109 by detecting `OSError` that may result from Apple silicon trying to use `phreeqpython`. `phreeqpython` and PHREEQC itself do not support ARM64 as far as I can tell, but we can at least detect this situation and allow everything in `Solution` that does not depend on `phreeqpython` to work.
=> Testing, documentation, and exception handling for Apple Silicon

.pre-commit-config.yaml, CHANGELOG.md, src/pyEQL/solute.py, src/pyEQL/solution.py, tests/test_phreeqc.py, tests/test_solution.py
Closes #116 by improving handling of unknown oxidation states.
Also bumps pre-commit versions (unrelated)
=> Solution: fixes failures when oxi state is unknown

CHANGELOG.md, src/pyEQL/engines.py, tests/test_phreeqc.py
This PR fixes an issue in which repeated calls to `equilibrate` when using `NativeEOS` or `PHREEQCEOS` would
change the mass of the `Solution` slightly. This was attributed to the fact that `pyEQL` and `PHREEQC` use slightly
different molecular weights for water.
=> NativeEOS: ensure equilibrate does not change solvent mass

CHANGELOG.md, src/pyEQL/solution.py, src/pyEQL/utils.py
`Solution.get_total_amount` would still fail if `ppm` was passed as a unit.
=> Solution.get_total_amount: fix error on ppm unit

src/pyEQL/equilibrium.py
This is yet another super minor fix. Here, I have fixed a missing close parenthesis in a docstring with a `ln()`.
I was just curious about the features in pyEQL and this caught my eye, so I had to fix it. 😅
=> Fix a missing close parenthesis in docstring

CHANGELOG.md, pyproject.toml, setup.cfg, src/pyEQL/activity_correction.py, src/pyEQL/engines.py, src/pyEQL/equilibrium.py, src/pyEQL/functions.py, src/pyEQL/solution.py, tests/test_phreeqc.py
Fixes #141 . This was ultimately caused by a subtle problem with charge balancing when elements with multiple oxidation states (at least, as recognized by `oxi_state_guesses`) were present in the `Solution`.
=> Fix charge balancing error and dependency housekeeping

CHANGELOG.md, src/pyEQL/database/pyeql_db.json
the `size.radius_ionic` for `Cr[+3]` and `Ni[+2]` was missing units. This PR adds them.
=> DB: add missing units to radius_ionic for Cr+3 and Ni+2

CHANGELOG.md
This is to work around an erroneous (now deleted) v1.1.0 release a few weeks back, since PyPi doesn't allow reuse of filenames.
=> bump ver to 1.1.1 for PyPI

CHANGELOG.md, src/pyEQL/engines.py, src/pyEQL/solution.py, tests/test_solution.py
- `Solution`: Fix a bug in which setting `balance_charge` to `pH` could result in
negative concentration errors when charge balancing or after `equilibrate` was
called. `Solution` now correctly enforces the ion product of water (Kw=1e-14)
whenever adjusting the amounts of H+ or OH- for charge balancing.
- `Solution._adjust_charge_balance`: Added a privat helper method to consolidate charge
balancing code used in `__init__` and `equilibrate`.
=> Solution: fix pH charge balancing bug and possible water ion imbalance

CHANGELOG.md, src/pyEQL/solution.py
- `Solution`: Hotfix to remove a stray `assert` statement in `_adjust_charge_balance`
that would sometimes cause errors in`pH` charge balancing.
=> Hotfix v1.1.5 - remove stray assert statement

src/pyEQL/solution.py
Description: 
- Edited the log message at `line 2298` to remove the redundant log message “Solution is not electroneutral (C.B. = {cb} eq/L).”
Minor changes:
- Updated the log message at `line 2298` to `self.logger.info(f"Adjusting {self._cb_species} to compensate.")`
- The separate log message at `line 2291` remains as `self.logger.info(f"Solution is not electroneutral (C.B. = {cb} eq/L).")`
=> Refactor logging for `_adjust_charge_balance`

.github/workflows/post-process.yml
Major changes:
- fix 1: updated python-version line 48 and removed dev
=> updated python-version line 48 and removed dev

pyproject.toml
Follow up to #163 , this PR set minimum versions of various dependencies so that `lowest-direct` dependency resolution successfully installs `pyEQL`.
=> set minimum dependency versions

src/pyEQL/functions.py, tests/test_functions.py
Major changes:
- feature 1: Revise 'Mixing Functions' documentation
- fix 1: Remove `T` from mixing entropy equation
- fix 2: Add explanations of activity and molar ratio for Gibbs free energy and entropy equation, respectively
- fix 3: Revise the unit of mixing entropy from `Joules` to `Joules per Kelvin`
- fix 4: Correct the error that prevents the formula from being displayed in the `donnan_eql()` documentation.
=> Revise 'Mixing Functions' documentation

AUTHORS.md, CHANGELOG.md, src/pyEQL/solution.py, src/pyEQL/utils.py, tests/test_solution.py, tests/test_utils.py
Fixes a subtle bug that caused `get_total_amount` to fail when passed an element with no oxidation state (such as `N`) that also occurs as part of another element name (such as `Na`)
Also improves formatting of ammonium sulfate salts in `standardize_formula`.
=> Bugfix in get_total_amount; CHANGELOG for next version

.github/workflows/post-process.yml, .github/workflows/testing.yaml, .github/workflows/upgrade_dependencies.yml, README.md, docs/requirements.txt, pyproject.toml, tests/test_phreeqc.py
Major changes:
- fix 1: bump `pymatgen` version to 2024.9.10 after bugfix
- fix 2: drop support for `python 3.9` following `numpy` [policy](https://numpy.org/neps/nep-0029-deprecation_policy.html)
Issue #158
=> pymatgen>=2024.9.10 updated after bugfix and conflict resolve

src/pyEQL/activity_correction.py
Major changes: 
Change documentation of "debye_parameter_B" from "A" to "B"
```sh
```
=> change documentation of debye_parameter_B

docs/class_solution.md
Changes:
- Fixes #195 
```sh
```
=> Documentation minor fixes

pyproject.toml
our `pytest` configuration uses `filterwarnings` to turn most warnings into errors, but `FutureWarning` should not be included in that behavior.
=> CI: don't fail on FutureWarning

CHANGELOG.md, pyproject.toml
- Bump `pint` to `0.24.1` for `numpy` `v2.0` compatibility and to mitigate CI issues
=> bump pint to 0.24.1

tests/test_solution.py
- Used `importlib` to locate `seawater.yaml`.
=> Using importlib to locate seawater.yaml

docs/contributing.md
Major changes:
- fix: Reference to quacc package changed to pyEQL
```sh
```
=> Fix typos in contributing.md

CHANGELOG.md, pyproject.toml
Major changes:
- fix: Remove python 3.9 classifier from pyproject.toml since package requires Python >=3.10
```sh
```
=> Update Python version classifiers in pyproject.toml

src/pyEQL/solution.py
Major changes:
- feature: closes #230
=> Clarify definition of pE vs. redox potential in documentation

.pre-commit-config.yaml
Major changes:
closes #257 
- updates syntax used in `.pre-commit-config.yaml` for pre-commit hooks
- updates pre-commit hook versions for black, codespell, ruff, pre-commit using `pre-commit autoupdate`
=> Update pre commit configuration

src/pyEQL/pourbaix/pourbaix_diagram.py
- This PR introduces a multi-stoichiometry capability to the `comp_dict` which enables it to handle a list of defined compositions.
- A `pytest` test suite is required for the testing of the multistoichiometry `comp_dict` feature.
=> Added Multistoichiometry_PourbaixDiagram Class

CHANGELOG.md, pyproject.toml
bump pymatgen to v.2025.1.9 to avoid a `DeprecationWarning` from causing the CI tests (post-merge) to fail.
=> bump pymatgen to v2025.1.9

src/pyEQL/utils.py, tests/test_utils.py
Follow up to #264 . The previous PR did not include the character U+2212
=> standardize_formula: handle ambiguous dash-hyphens pt.2
